chore: new branch

diff --git a/.github/hooks/commit-msg b/.github/hooks/commit-msg
--- a/.github/hooks/commit-msg
+++ b/.github/hooks/commit-msg
@@ -6,10 +6,10 @@ COMMIT_MSG=$(cat "$COMMIT_MSG_FILE")
 PATTERN="^(feat|fix|docs|style|refactor|test|chore|Mergeback): .+"
 
 if [[ ! $COMMIT_MSG =~ $PATTERN ]]; then
-    echo "❌ ERROR: Mensaje de commit inválido."
-    echo "Debe seguir el formato: feat: mensaje, fix: mensaje, docs: mensaje, styles: mensaje."
-    exit 1  # Cancela el commit
+    echo "❌ ERROR: Commit message no valid."
+    echo "Please follow the next format: feat: message, fix: menssage, docs: menssage, styles: message, refactor: message, test: message, chore: message, mergeback: message."
+    exit 1
 fi
 
-echo "✅ Mensaje de commit válido."
-exit 0  # Permite el commit
+echo "✅ Commit message valid."
+exit 0
